/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdoptRouteImport } from './routes/_authenticated/adopt'
import { Route as AuthenticatedContactRouteImport } from './routes/_authenticated/contact'
import { Route as AuthenticatedCsrRouteImport } from './routes/_authenticated/csr'
import { Route as AuthenticatedDonateRouteImport } from './routes/_authenticated/donate'
import { Route as AuthenticatedFosterRouteImport } from './routes/_authenticated/foster'
import { Route as AuthenticatedGeopetIdRouteImport } from './routes/_authenticated/geopet-id'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedPawsOfIndiaRouteImport } from './routes/_authenticated/paws-of-india'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedProgrammesRouteImport } from './routes/_authenticated/programmes'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'
import { Route as AuthenticatedSchoolsRouteImport } from './routes/_authenticated/schools'
import { Route as AuthenticatedTransparencyRouteImport } from './routes/_authenticated/transparency'
import { Route as AuthenticatedVolunteerRouteImport } from './routes/_authenticated/volunteer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdoptRoute = AuthenticatedAdoptRouteImport.update({
  id: '/adopt',
  path: '/adopt',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactRoute = AuthenticatedContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCsrRoute = AuthenticatedCsrRouteImport.update({
  id: '/csr',
  path: '/csr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDonateRoute = AuthenticatedDonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFosterRoute = AuthenticatedFosterRouteImport.update({
  id: '/foster',
  path: '/foster',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGeopetIdRoute = AuthenticatedGeopetIdRouteImport.update({
  id: '/geopet-id',
  path: '/geopet-id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPawsOfIndiaRoute =
  AuthenticatedPawsOfIndiaRouteImport.update({
    id: '/paws-of-india',
    path: '/paws-of-india',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgrammesRoute = AuthenticatedProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchoolsRoute = AuthenticatedSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransparencyRoute =
  AuthenticatedTransparencyRouteImport.update({
    id: '/transparency',
    path: '/transparency',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVolunteerRoute = AuthenticatedVolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AuthenticatedAboutRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/adopt': typeof AuthenticatedAdoptRoute
  '/contact': typeof AuthenticatedContactRoute
  '/csr': typeof AuthenticatedCsrRoute
  '/donate': typeof AuthenticatedDonateRoute
  '/foster': typeof AuthenticatedFosterRoute
  '/geopet-id': typeof AuthenticatedGeopetIdRoute
  '/home': typeof AuthenticatedHomeRoute
  '/paws-of-india': typeof AuthenticatedPawsOfIndiaRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/programmes': typeof AuthenticatedProgrammesRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/schools': typeof AuthenticatedSchoolsRoute
  '/transparency': typeof AuthenticatedTransparencyRoute
  '/volunteer': typeof AuthenticatedVolunteerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AuthenticatedAboutRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/adopt': typeof AuthenticatedAdoptRoute
  '/contact': typeof AuthenticatedContactRoute
  '/csr': typeof AuthenticatedCsrRoute
  '/donate': typeof AuthenticatedDonateRoute
  '/foster': typeof AuthenticatedFosterRoute
  '/geopet-id': typeof AuthenticatedGeopetIdRoute
  '/home': typeof AuthenticatedHomeRoute
  '/paws-of-india': typeof AuthenticatedPawsOfIndiaRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/programmes': typeof AuthenticatedProgrammesRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/schools': typeof AuthenticatedSchoolsRoute
  '/transparency': typeof AuthenticatedTransparencyRoute
  '/volunteer': typeof AuthenticatedVolunteerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/adopt': typeof AuthenticatedAdoptRoute
  '/_authenticated/contact': typeof AuthenticatedContactRoute
  '/_authenticated/csr': typeof AuthenticatedCsrRoute
  '/_authenticated/donate': typeof AuthenticatedDonateRoute
  '/_authenticated/foster': typeof AuthenticatedFosterRoute
  '/_authenticated/geopet-id': typeof AuthenticatedGeopetIdRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/paws-of-india': typeof AuthenticatedPawsOfIndiaRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/programmes': typeof AuthenticatedProgrammesRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/_authenticated/schools': typeof AuthenticatedSchoolsRoute
  '/_authenticated/transparency': typeof AuthenticatedTransparencyRoute
  '/_authenticated/volunteer': typeof AuthenticatedVolunteerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/adopt'
    | '/contact'
    | '/csr'
    | '/donate'
    | '/foster'
    | '/geopet-id'
    | '/home'
    | '/paws-of-india'
    | '/profile'
    | '/programmes'
    | '/roadmap'
    | '/schools'
    | '/transparency'
    | '/volunteer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/adopt'
    | '/contact'
    | '/csr'
    | '/donate'
    | '/foster'
    | '/geopet-id'
    | '/home'
    | '/paws-of-india'
    | '/profile'
    | '/programmes'
    | '/roadmap'
    | '/schools'
    | '/transparency'
    | '/volunteer'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/about'
    | '/_authenticated/admin'
    | '/_authenticated/adopt'
    | '/_authenticated/contact'
    | '/_authenticated/csr'
    | '/_authenticated/donate'
    | '/_authenticated/foster'
    | '/_authenticated/geopet-id'
    | '/_authenticated/home'
    | '/_authenticated/paws-of-india'
    | '/_authenticated/profile'
    | '/_authenticated/programmes'
    | '/_authenticated/roadmap'
    | '/_authenticated/schools'
    | '/_authenticated/transparency'
    | '/_authenticated/volunteer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/adopt': {
      id: '/_authenticated/adopt'
      path: '/adopt'
      fullPath: '/adopt'
      preLoaderRoute: typeof AuthenticatedAdoptRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contact': {
      id: '/_authenticated/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AuthenticatedContactRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/csr': {
      id: '/_authenticated/csr'
      path: '/csr'
      fullPath: '/csr'
      preLoaderRoute: typeof AuthenticatedCsrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/donate': {
      id: '/_authenticated/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof AuthenticatedDonateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/foster': {
      id: '/_authenticated/foster'
      path: '/foster'
      fullPath: '/foster'
      preLoaderRoute: typeof AuthenticatedFosterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/geopet-id': {
      id: '/_authenticated/geopet-id'
      path: '/geopet-id'
      fullPath: '/geopet-id'
      preLoaderRoute: typeof AuthenticatedGeopetIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/paws-of-india': {
      id: '/_authenticated/paws-of-india'
      path: '/paws-of-india'
      fullPath: '/paws-of-india'
      preLoaderRoute: typeof AuthenticatedPawsOfIndiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programmes': {
      id: '/_authenticated/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof AuthenticatedProgrammesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schools': {
      id: '/_authenticated/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof AuthenticatedSchoolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transparency': {
      id: '/_authenticated/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof AuthenticatedTransparencyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/volunteer': {
      id: '/_authenticated/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof AuthenticatedVolunteerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdoptRoute: typeof AuthenticatedAdoptRoute
  AuthenticatedContactRoute: typeof AuthenticatedContactRoute
  AuthenticatedCsrRoute: typeof AuthenticatedCsrRoute
  AuthenticatedDonateRoute: typeof AuthenticatedDonateRoute
  AuthenticatedFosterRoute: typeof AuthenticatedFosterRoute
  AuthenticatedGeopetIdRoute: typeof AuthenticatedGeopetIdRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedPawsOfIndiaRoute: typeof AuthenticatedPawsOfIndiaRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProgrammesRoute: typeof AuthenticatedProgrammesRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedSchoolsRoute: typeof AuthenticatedSchoolsRoute
  AuthenticatedTransparencyRoute: typeof AuthenticatedTransparencyRoute
  AuthenticatedVolunteerRoute: typeof AuthenticatedVolunteerRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdoptRoute: AuthenticatedAdoptRoute,
  AuthenticatedContactRoute: AuthenticatedContactRoute,
  AuthenticatedCsrRoute: AuthenticatedCsrRoute,
  AuthenticatedDonateRoute: AuthenticatedDonateRoute,
  AuthenticatedFosterRoute: AuthenticatedFosterRoute,
  AuthenticatedGeopetIdRoute: AuthenticatedGeopetIdRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedPawsOfIndiaRoute: AuthenticatedPawsOfIndiaRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProgrammesRoute: AuthenticatedProgrammesRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedSchoolsRoute: AuthenticatedSchoolsRoute,
  AuthenticatedTransparencyRoute: AuthenticatedTransparencyRoute,
  AuthenticatedVolunteerRoute: AuthenticatedVolunteerRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
